# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  jj2020infra:
    image: jj2020infra
    build:
      context: .
      dockerfile: JJ2020.INFRA/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
